# Generated by Django 2.1.1 on 2018-10-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagarism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
